export const developmentURLs = {
  loginURL: "http://localhost/eggsplore-v-2/api/login.php",
  registerUserURL: "http://localhost/eggsplore-v-2/api/register.php",
  manageEggsURL: "http://localhost/eggsplore-v-2/api/egg_management.php",
  manageUserURL: "http://localhost/eggsplore-v-2/api/user_management.php",
  manageFeedsURL: "http://localhost/eggsplore-v-2/api/feeds_management.php",
  manageChickenURL: "http://localhost/eggsplore-v-2/api/chicken_management.php",
  manageMedicineURL: "http://localhost/eggsplore-v-2/api/medicine_management.php",
  manageBuildingURL: "http://localhost/eggsplore-v-2/api/building_management.php",
  manageLocationsURL: "http://localhost/eggsplore-v-2/api/locations_management.php",
  manageSalesURL: "http://localhost/eggsplore-v-2/api/sales_management.php",
  manageFinancialsURL: "http://localhost/eggsplore-v-2/api/financial_management.php",
  manageDeliveryURL: "http://localhost/eggsplore-v-2/api/delivery_monitoring.php",
};
export const buildURLs = {
  manageLocationsURL: "https://edwinandlinafarm.com/api/locations_management.php",
  manageFinancialsURL: "https://edwinandlinafarm.com/api/financial_management.php",
  manageDeliveryURL: "https://edwinandlinafarm.com/api/delivery_monitoring.php",
  manageBuildingURL: "https://edwinandlinafarm.com/api/building_management.php",
  manageMedicineURL: "https://edwinandlinafarm.com/api/medicine_management.php",
  manageChickenURL: "https://edwinandlinafarm.com/api/chicken_management.php",
  manageFeedsURL: "https://edwinandlinafarm.com/api/feeds_management.php",
  manageSalesURL: "https://edwinandlinafarm.com/api/sales_management.php",
  manageUserURL: "https://edwinandlinafarm.com/api/user_management.php",
  manageEggsURL: "https://edwinandlinafarm.com/api/egg_management.php",
  registerUserURL: "https://edwinandlinafarm.com/api/register.php",
  loginURL: "https://edwinandlinafarm.com/api/login.php",
};
