export const developmentURLs = {
  loginURL: "http://localhost/eggsplore-v-2/api/login.php",
  registerUserURL: "http://localhost/eggsplore-v-2/api/register.php",
  manageEggsURL: "http://localhost/eggsplore-v-2/api/egg_management.php",
  manageUserURL: "http://localhost/eggsplore-v-2/api/user_management.php",
  manageFeedsURL: "http://localhost/eggsplore-v-2/api/feeds_management.php",
  manageChickenURL: "http://localhost/eggsplore-v-2/api/chicken_management.php",
  manageMedicineURL: "http://localhost/eggsplore-v-2/api/medicine_management.php",
  manageBuildingURL: "http://localhost/eggsplore-v-2/api/building_management.php",
  manageLocationsURL: "http://localhost/eggsplore-v-2/api/locations_management.php",
  manageSalesURL: "http://localhost/eggsplore-v-2/api/sales_management.php",
  manageFinancialsURL: "http://localhost/eggsplore-v-2/api/financial_management.php",
  manageDeliveryURL: "http://localhost/eggsplore-v-2/api/delivery_monitoring.php",
};
export const buildURLs = {
  manageLocationsURL: "../api/locations_management.php",
  manageFinancialsURL: "../api/financial_management.php",
  manageDeliveryURL: "../api/delivery_monitoring.php",
  manageBuildingURL: "../api/building_management.php",
  manageMedicineURL: "../api/medicine_management.php",
  manageChickenURL: "../api/chicken_management.php",
  manageFeedsURL: "../api/feeds_management.php",
  manageSalesURL: "../api/sales_management.php",
  manageUserURL: "../api/user_management.php",
  manageEggsURL: "../api/egg_management.php",
  registerUserURL: "../api/register.php",
  loginURL: "../api/login.php",
};
